[build]
  publish = "."
  
[[redirects]]
  from = "/"
  to = "/html/splash.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/html/index.html"
  status = 404
